version: 2

#define sources from the TPC-H data is taken and details about the source tables
sources:
  - name: TPC-H
    tables:
      - name: Orders
        columns: 
          - name: O_ORDERKEY
          - name: O_CUSTKEY
          - name: O_ORDERSTATUS
          - name: O_TOTALPRICE
          - name: O_ORDERDATE
          - name: O_ORDER-PRIORITY
          - name: O_CLERK
          - name: O_SHIP-PRIORITY
          - name: O_COMMENT
      
      - name: LineItem
        columns: 
          - name: L_ORDERKEY
          - name: L_PARTKEY
          - name: L_SUPPKEY
          - name: L_LINENUMBER
          - name: L_QUANTITY
          - name: L_EXTENDEDPRICE
          - name: L_DISCOUNT
          - name: L_TAX
          - name: L_RETURNFLAG
          - name: L_LINESTATUS
          - name: L_SHIPDATE
          - name: L_COMMITDATE
          - name: L_RECEIPTDATE
          - name: L_SHIPINSTRUCT
          - name: L_SHIPMODE
          - name: L_COMMENT

      - name: REGION
        columns: 
          - name: R_REGIONKEY
          - name: R_NAME
          - name: R_COMMENT
      
      - name: PARTSUPP
        columns: 
          - name: PS_PARTKEY
          - name: PS_SUPPKEY
          - name: PS_AVAILQTY
          - name: PS_SUPPLYCOST
          - name: PS_COMMENT

      - name: CUSTOMER
        columns: 
          - name: C_CUST_KEY
          - name: C_NAME
          - name: C_ADDRESS
          - name: C_NATIONKEY
          - name: C_PHONE
          - name: C_ACCTBAL
          - name: C_MKTSEGMENT
          - name: C_COMMENT

      - name: NATION
        columns: 
          - name: N_NATIONKEY
          - name: N_NAME
          - name: N_REGIONKEY
          - name: N_COMMENT

      - name: PART
        columns: 
          - name: P_PARTKEY
          - name: P_NAME
          - name: P_MFGR
          - name: P_BRAND
          - name: P_TYPE
          - name: P_SIZE
          - name: P_CONTAINER
          - name: P_RETAILPRICE
          - name: P_COMMENT
        
      - name: SUPPLIER
        columns: 
          - name: S_SUPPKEY
          - name: S_NAME
          - name: S_ADDRESS
          - name: S_NATIONKEY
          - name: S_PHONE
          - name: S_ACCTBAL
          - name: S_COMMENT
        


    
